<?php

namespace App\Enums;

use App\Traits\CommonEnumMethodsTrait;

enum ResponseMessageEnum: string
{
    use CommonEnumMethodsTrait;

    case BAD_REQUEST = 'BAD REQUEST';
    case NOT_FOUND = 'NOT FOUND';
    case NO_CONTENT = "";
    case SUCCESS = 'SUCCESS';
    case SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
    case SUCCESSFULLY_LOGGED_IN = 'SUCCESSFULLY LOGGED IN';
    case SUCCESSFULLY_LOGGED_OUT = 'SUCCESSFULLY LOGGED OUT';
    case SUCCESSFULLY_SAVED = 'SUCCESSFULLY SAVED';
    case SUCCESSFULLY_FETCHED = 'SUCCESSFULLY FETCHED';
    case SUCCESSFULLY_UPDATED = 'SUCCESSFULLY UPDATED';
    case SUCCESSFULLY_DELETED = 'SUCCESSFULLY DELETED';
    case SUCCESSFULLY_DETACHED = 'SUCCESSFULLY DETACHED';
    case SUCCESSFULLY_SAVED_MEDIA = 'SUCCESSFULLY SAVED MEDIA';
    case SUCCESSFULLY_UPDATED_MEDIA = 'SUCCESSFULLY UPDATED MEDIA';
    case SUCCESSFULLY_DELETED_MEDIA = 'SUCCESSFULLY DELETED MEDIA';
    case NOT_SAVED = 'NOT SAVED';
    case ERROR_OCCURRED = 'ERROR OCCURRED';
}
